#!/bin/bash

if [[ "$#" -ge 1 ]]; then
	Godot_v4.3-stable_win64_console.exe "$@"
else
	cd "/mnt/d/Program Files (x86)/Godot/Projects"
	ls -1 | cat -n 
	echo "Select a project: [1-n]"
	read project
	project=$(ls -m | awk -F ', ' "{print \$$project}")
	cd "$project"
fi
