#!/bin/bash

if [[ "$1" == "--set-projects-path" ]]; then
	sed -i '1s%.*%'"$2%" ~/.godot
elif [[ "$1" == "--set-executable-path" ]]; then
	sed -i '2s%.*%'"$2%" ~/.godot
elif [[ "$#" -ge 1 ]]; then
	"$(tail -n 1 ~/.godot)" "$@"
else
	cd "$(head -n 1 ~/.godot)"
	ls -1 | cat -n 
	echo "Select a project: [1-n] (use --set-path to change projects path)"
	read project
	project=$(ls -1 | awk -F '\\n' "{if (NR==$project) print \$0}")
	cd "$project"
fi
