#!/bin/bash

if [[ $# -eq 0 ]]; then echo "usage: search [-d directory] [-n name-pattern] [-c context] search-terms"; exit 0; fi

NAME=""
DIR="."
CONTEXT="0"

while [[ "$1" =~ "-" ]]; do
	if [[ "$1" = "-n" ]]; then
		NAME="$2"
		shift 2
	elif [[ "$1" = "-d" ]]; then
		DIR="$2"
		shift 2
	elif [[ "$1" = "-c" ]]; then
		CONTEXT="$2"
		shift 2
	fi
done

if [[ "$NAME" != "" ]]; then
	echo find "$DIR" -type f -name "$NAME" -exec grep -C "$CONTEXT" -nHE "$@" {} \;
	find "$DIR" -type f -name "$NAME" -exec grep -C "$CONTEXT" -nHE "$@" {} \;
else
	echo find "$DIR" -type f -exec grep -C "$CONTEXT" -nHE "$@" {} \;
	find "$DIR" -type f -exec grep -C "$CONTEXT" -nHE "$@" {} \;
fi
