#!/bin/bash

if [[ $# -eq 0 ]]; then echo "usage: search [-d directory] [-n name-pattern] [-t|e (file) type/extension] [-c context] [-f | --filename-only] [-v | --verbose] search-terms"; exit 0; fi

NAME=""
DIR="."
CONTEXT="0"
FILENAME=""
VERBOSE=0

while [[ "$1" =~ "-" ]]; do
	if [[ "$1" = "-d"* ]]; then
		DIR="$2"
		shift 2
	elif [[ "$1" = "-n"* ]]; then
		NAME="$2"
		shift 2
	elif [[ "$1" = "-t"* ]] || [[ "$1" = "-e"* ]]; then
		NAME="*.$2"
		shift 2
	elif [[ "$1" = "-c"* ]]; then
		CONTEXT="$2"
		shift 2
	elif [[ "$1" = "-f"* ]]; then
		FILENAME="l"
		shift 1
	elif [[ "$1" = "-v"* ]]; then
		VERBOSE=1
		shift 1
	else
		break
	fi
done

if [[ "$NAME" != "" ]]; then
	if [[ $VERBOSE -ne 0 ]]; then
		echo find "$DIR" -type f -name "$NAME" -exec grep -C "$CONTEXT" -nHE "$@" {} \;
	fi
	find "$DIR" -type f -name "$NAME" -exec grep -C "$CONTEXT" -n"$FILENAME"HE "$@" {} \;
else
	if [[ $VERBOSE -ne 0 ]]; then
		echo find "$DIR" -type f -exec grep -C "$CONTEXT" -nHE "$@" {} \;
	fi
	find "$DIR" -type f -exec grep -C "$CONTEXT" -n"$FILENAME"HE "$@" {} \;
fi
