#!/bin/bash

# Prereqs
sudo apt update

# Setup vim
curl -L https://raw.githubusercontent.com/alegottu/linux-config/main/.vimrc -o ~/.vimrc
curl -Lo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
curl -sL install-node.vercel.app/lts | bash
echo "Reload .vimrc and :PlugInstall to install plugins."

# Setup bash
curl -L https://raw.githubusercontent.com/alegottu/linux-config/main/.bashrc -o ~/.bashrc
sudo apt install ranger
sudo apt install keychain
