#!/bin/bash

# vim
curl -L https://raw.githubusercontent.com/alegottu/linux-config/main/.vimrc -o ~/.vimrc
curl -Lo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo "Reload .vimrc and :PlugInstall to install plugins."

# nvim
curl -Lo ~/.config/nvim/init.lua --create-dirs \ 
    https://raw.githubusercontent.com/alegottu/linux-config/main/init.lua

# bash
curl -L https://raw.githubusercontent.com/alegottu/linux-config/main/.bashrc -o ~/.bashrc

# tmux
curl -L https://raw.githubusercontent.com/alegottu/linux-config/main/.tmux.conf -o ~/.tmux.conf
