#!/bin/bash
# Make sure permissions of this file are not writeable so that you can't just edit it remotely before logging in

cd ~

START_MINUTES=420 # 7:00 AM
DEADLINE_MINUTES=605 # 10:05 AM
file_mod_minutes=$(expr `date -r .last_login +%H` \* 60 + `date -r .last_login +%M`)

if [[ $file_mod_minutes -lt $START_MINUTES ]] || [[ $file_mod_minutes -gt $DEADLINE_MINUTES ]]; then
	echo "No cheating"
	cd ~/Projects/Rust/discord-bot/
	cargo run send
	exit
fi

last_login_day=$(cat .last_login) # M/D/Y
current_day=$(date +%D)
current_minutes=$(expr `date +%H` \* 60 + `date +%M`)

if [[ $last_login_day == $current_day ]] || [[ $current_minutes -lt $START_MINUTES ]]; then
	exit
fi

echo $current_day > .last_login

if [[ $current_minutes -gt $DEADLINE_MINUTES ]]; then
	echo "Yikes"
	cd ~/Projects/Rust/discord-bot/
	cargo run send
else
	echo "Ride on time"
fi
